[package]
name = "fugo-sass"
description = "A Sass compiler written purely in Rust"
readme = "../../README.md"
categories = ["command-line-utilities", "web-programming"]
include = [
    "src",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "Cargo.lock",
    "LICENSE",
]
default-run = "fugo-sass"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true

[[bin]]
name = "fugo-sass"
path = "src/main.rs"
required-features = ["commandline"]

[lib]
name = "fugo_sass"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
bench = false


[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --features=macro --no-deps --open
features = ["macro"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
wasm-bindgen = { workspace = true, optional = true }
fugo-sass-compiler.workspace = true
fugo-sass-macro = { workspace = true, optional = true }
clap = { workspace = true, optional = true }

[features]
# todo: no commandline by default
default = ["commandline", "random"]
# Option (enabled by default): build a binary using clap
commandline = ["clap"]
random = ["fugo-sass-compiler/random"]
wasm-exports = ["fugo-sass-compiler/wasm-exports", "wasm-bindgen"]
# Option: include the proc macro `fugo_sass::include!`
macro = ["fugo-sass-macro"]
nightly = ["fugo-sass-macro/nightly"]

# Random numbers in WebAssembly come from JavaScript.
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["wasm_js"] }

[dev-dependencies]
tempfile.workspace = true
paste.workspace = true
