[package]
name = "fugo-sass"
version = "0.14.0"
description = "A Sass compiler written purely in Rust"
readme = "../../README.md"
license = "MIT"
categories = ["command-line-utilities", "web-programming"]
keywords = ["scss", "sass", "css", "web"]
repository = "https://github.com/getfugo/fugo-sass"
authors = ["Connor Skees <39542938+ConnorSkees@users.noreply.github.com>", "The fugo-sass authors"]
edition = "2021"
include = [
    "src",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "Cargo.lock",
    "LICENSE",
]
default-run = "fugo-sass"
rust-version = "1.70"

[[bin]]
name = "fugo-sass"
path = "src/main.rs"
required-features = ["commandline"]

[lib]
name = "fugo_sass"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
bench = false


[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --features=macro --no-deps --open
features = ["macro"]
rustdoc-args = ["--cfg", "doc_cfg"]

[dependencies]
wasm-bindgen = { version = "0.2", optional = true }
getrandom = { version = "0.2", features = ["js"] }
fugo-sass-compiler = { path = "../compiler", version = "=0.14.0", default-features = false }
fugo-sass-macro = { path = "../include_sass", version = "=0.14.0", optional = true }
clap = { version = "4.3.10", optional = true }

[features]
# todo: no commandline by default
default = ["commandline", "random"]
# Option (enabled by default): build a binary using clap
commandline = ["clap"]
random = ["fugo-sass-compiler/random"]
wasm-exports = ["fugo-sass-compiler/wasm-exports", "wasm-bindgen"]
# Option: include the proc macro `fugo_sass::include!`
macro = ["fugo-sass-macro"]
nightly = ["fugo-sass-macro/nightly"]

[dev-dependencies]
tempfile = "3.3.0"
paste = "1.0.3"
