[package]
name = "fugo-sass-compiler"
description = "The compiler behind fugo-sass, a Sass compiler written in Rust: its internals, with frequent breaking changes"
readme = "README.md"
categories = ["web-programming"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true

[lib]
name = "fugo_sass_compiler"
path = "src/lib.rs"
# crate-type = ["cdylib", "rlib"]
bench = false

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --no-deps --open
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# todo: use xorshift for random numbers
rand = { workspace = true, optional = true }
# todo: update to use asref<path>
# todo: update to expose more info (for eww)
# todo: update to use text_size::TextRange
codemap.workspace = true
wasm-bindgen = { workspace = true, optional = true }
# todo: benchmark using phf for global functions
phf = { workspace = true, features = ["macros"] }
indexmap.workspace = true
# todo: do we really need interning for things?
lasso.workspace = true

[features]
default = ["random", "custom-builtin-fns"]
# Option (enabled by default): enable the builtin functions `random([$limit])` and `unique-id()`
random = ["rand"]
# Option: expose JavaScript-friendly WebAssembly exports
wasm-exports = ["wasm-bindgen"]
# Option: expose internals necessary to implement custom builtin functions
custom-builtin-fns = []
