[package]
name = "fugo-sass-macro"
description = "The proc macro behind fugo_sass::include!"
readme = "../../README.md"
categories = ["web-programming"]
include = ["src", "Cargo.toml", "LICENSE"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["parsing", "printing", "proc-macro"] }
# The compiler's default features.
fugo-sass-compiler = { workspace = true, features = ["random", "custom-builtin-fns"] }
quote.workspace = true

[features]
nightly = []
