[package]
name = "fugo-sass-spec"
version = "0.0.0"
description = "Runs sass-spec, the official Sass test suite, against fugo-sass"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "fugo-sass-spec"
path = "src/main.rs"

[dependencies]
fugo-sass-compiler = { workspace = true, features = ["random"] }
